---
# website::tag::1:: Deploy the training/webapp Docker Container: https://hub.docker.com/r/training/webapp/

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-deployment
spec:
  selector:
    matchLabels:
      app: ollama
  replicas: 1
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
        - name: ollama
          image: ollama/ollama
          ports:
            - containerPort: 11434
---

kind: Service
apiVersion: v1
metadata:
  name: ollama-service
spec:
  selector:
    app: ollama
  ports:
    - protocol: TCP
      targetPort: 11434
      port: 11434
  type: LoadBalancer
